/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Standard connection string.  You must configure the [IP Access List](https://docs.pingcap.com/tidbcloud/connect-to-tidb-cluster#connect-via-standard-connection) for the cluster you created on [TiDB Cloud console](https://tidbcloud.com/) before connecting to this connection string.
*/
export class ClusterItemStatusConnectionStringsStandard {
    /**
    * The host of standard connection.
    */
    'host'?: string;
    /**
    * The TiDB port for connection. The port must be in the range of 1024-65535 except 10080.  **Limitations**: - For a Developer Tier cluster, only port `4000` is available.
    */
    'port'?: number = 4000;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ClusterItemStatusConnectionStringsStandard.attributeTypeMap;
    }
}

