/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItemConfig } from './clusterItemConfig';
import { ClusterItemStatus } from './clusterItemStatus';

/**
* ClusterItem is the information of cluster.
*/
export class ClusterItem {
    /**
    * The ID of the cluster.
    */
    'id': string;
    /**
    * The ID of the project.
    */
    'projectId': string;
    /**
    * The name of the cluster.
    */
    'name'?: string;
    /**
    * The cluster type: - `\"DEVELOPER\"`: a [Developer Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#developer-tier) cluster - `\"DEDICATED\"`: a [Dedicated Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#dedicated-tier) cluster.
    */
    'clusterType'?: ClusterItem.ClusterTypeEnum;
    /**
    * The cloud provider on which your TiDB cluster is hosted. - `\"AWS\"`: the Amazon Web Services cloud provider - `\"GCP\"`: the Google Cloud Platform cloud provider
    */
    'cloudProvider'?: ClusterItem.CloudProviderEnum;
    /**
    * Region of the cluster.
    */
    'region'?: string;
    /**
    * The creation time of the cluster in Unix timestamp seconds (epoch time).
    */
    'createTimestamp'?: string;
    'config'?: ClusterItemConfig;
    'status'?: ClusterItemStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "clusterType",
            "baseName": "cluster_type",
            "type": "ClusterItem.ClusterTypeEnum"
        },
        {
            "name": "cloudProvider",
            "baseName": "cloud_provider",
            "type": "ClusterItem.CloudProviderEnum"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "createTimestamp",
            "baseName": "create_timestamp",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "ClusterItemConfig"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ClusterItemStatus"
        }    ];

    static getAttributeTypeMap() {
        return ClusterItem.attributeTypeMap;
    }
}

export namespace ClusterItem {
    export enum ClusterTypeEnum {
        Dedicated = <any> 'DEDICATED',
        Developer = <any> 'DEVELOPER'
    }
    export enum CloudProviderEnum {
        Aws = <any> 'AWS',
        Gcp = <any> 'GCP'
    }
}
