/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItemStatusConnectionStringsStandard } from './clusterItemStatusConnectionStringsStandard';
import { ClusterItemStatusConnectionStringsVpcPeering } from './clusterItemStatusConnectionStringsVpcPeering';

/**
* Connection strings.
*/
export class ClusterItemStatusConnectionStrings {
    /**
    * The default TiDB user for connection.
    */
    'defaultUser'?: string;
    'standard'?: ClusterItemStatusConnectionStringsStandard;
    'vpcPeering'?: ClusterItemStatusConnectionStringsVpcPeering;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "defaultUser",
            "baseName": "default_user",
            "type": "string"
        },
        {
            "name": "standard",
            "baseName": "standard",
            "type": "ClusterItemStatusConnectionStringsStandard"
        },
        {
            "name": "vpcPeering",
            "baseName": "vpc_peering",
            "type": "ClusterItemStatusConnectionStringsVpcPeering"
        }    ];

    static getAttributeTypeMap() {
        return ClusterItemStatusConnectionStrings.attributeTypeMap;
    }
}

