/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItemStatusNodeMapTidbInner } from './clusterItemStatusNodeMapTidbInner';
import { ClusterItemStatusNodeMapTiflashInner } from './clusterItemStatusNodeMapTiflashInner';
import { ClusterItemStatusNodeMapTikvInner } from './clusterItemStatusNodeMapTikvInner';

/**
* Node map. The `node_map` is returned only when the `cluster_status` is `\"AVAILABLE\"` or `\"MODIFYING\"`.
*/
export class ClusterItemStatusNodeMap {
    /**
    * TiDB node map.
    */
    'tidb': Array<ClusterItemStatusNodeMapTidbInner>;
    /**
    * TiKV node map.
    */
    'tikv': Array<ClusterItemStatusNodeMapTikvInner>;
    /**
    * TiFlash node map.
    */
    'tiflash'?: Array<ClusterItemStatusNodeMapTiflashInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tidb",
            "baseName": "tidb",
            "type": "Array<ClusterItemStatusNodeMapTidbInner>"
        },
        {
            "name": "tikv",
            "baseName": "tikv",
            "type": "Array<ClusterItemStatusNodeMapTikvInner>"
        },
        {
            "name": "tiflash",
            "baseName": "tiflash",
            "type": "Array<ClusterItemStatusNodeMapTiflashInner>"
        }    ];

    static getAttributeTypeMap() {
        return ClusterItemStatusNodeMap.attributeTypeMap;
    }
}

