/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateClusterReqConfig } from './createClusterReqConfig';

/**
* CreateClusterReq is the request for creating cluster.
*/
export class CreateClusterReq {
    /**
    * The name of the cluster. The name must be 4-64 characters that can only include numbers, letters, and hyphens, and the first and last character must be a letter or number.
    */
    'name': string;
    /**
    * The cluster type. - `\"DEVELOPER\"`: create a [Developer Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#developer-tier) cluster - `\"DEDICATED\"`: create a [Dedicated Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#dedicated-tier) cluster. Before creating a Dedicated Tier cluster, you must [set a Project CIDR](https://docs.pingcap.com/tidbcloud/set-up-vpc-peering-connections#prerequisite-set-a-project-cidr) on [TiDB Cloud console](https://tidbcloud.com/).
    */
    'clusterType': CreateClusterReq.ClusterTypeEnum;
    /**
    * The cloud provider on which your TiDB cluster is hosted. - `\"AWS\"`: the Amazon Web Services cloud provider - `\"GCP\"`: the Google Cloud Platform cloud provider
    */
    'cloudProvider': CreateClusterReq.CloudProviderEnum;
    /**
    * The region value should match the cloud provider\'s region code. You can get the complete list of available regions from the response of [List the cloud providers, regions and available specifications](#tag/Cluster/operation/ListProviderRegions).  For the detailed information on each region, refer to the documentation of the corresponding cloud provider ([AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) | [GCP](https://cloud.google.com/about/locations#americas)).  For example, if you want to deploy the cluster in the Oregon region for AWS, set the value to `\"us-west-2\"`.
    */
    'region': string;
    'config': CreateClusterReqConfig;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "clusterType",
            "baseName": "cluster_type",
            "type": "CreateClusterReq.ClusterTypeEnum"
        },
        {
            "name": "cloudProvider",
            "baseName": "cloud_provider",
            "type": "CreateClusterReq.CloudProviderEnum"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "CreateClusterReqConfig"
        }    ];

    static getAttributeTypeMap() {
        return CreateClusterReq.attributeTypeMap;
    }
}

export namespace CreateClusterReq {
    export enum ClusterTypeEnum {
        Dedicated = <any> 'DEDICATED',
        Developer = <any> 'DEVELOPER'
    }
    export enum CloudProviderEnum {
        Aws = <any> 'AWS',
        Gcp = <any> 'GCP'
    }
}
