/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateClusterReqConfig } from './createClusterReqConfig';

/**
* CreateRestoreReq is the request for restoring backup to a new cluster.
*/
export class CreateRestoreReq {
    /**
    * The ID of the backup.
    */
    'backupId': string;
    /**
    * The name of the restored cluster. The restored cluster is the new cluster your backup data is restored to.  - The name must be 4-64 characters that only contain numbers, letters, and hyphens. The first and last character must be a letter or number. - This must be different from the name of the existing cluster.
    */
    'name': string;
    'config'?: CreateClusterReqConfig;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "backupId",
            "baseName": "backup_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "CreateClusterReqConfig"
        }    ];

    static getAttributeTypeMap() {
        return CreateRestoreReq.attributeTypeMap;
    }
}

