/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItemConfigComponentsTidb } from './clusterItemConfigComponentsTidb';
import { ClusterItemConfigComponentsTiflash } from './clusterItemConfigComponentsTiflash';
import { ClusterItemConfigComponentsTikv } from './clusterItemConfigComponentsTikv';

/**
* The components of the cluster.  **Limitations**: - For a Dedicated Tier cluster, the `components` parameter is **required**. - For a Developer Tier cluster, the `components` value is **ignored**. Setting this configuration does not have any effects.
*/
export class CreateClusterReqConfigComponents {
    'tidb': ClusterItemConfigComponentsTidb;
    'tikv': ClusterItemConfigComponentsTikv;
    'tiflash'?: ClusterItemConfigComponentsTiflash;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tidb",
            "baseName": "tidb",
            "type": "ClusterItemConfigComponentsTidb"
        },
        {
            "name": "tikv",
            "baseName": "tikv",
            "type": "ClusterItemConfigComponentsTikv"
        },
        {
            "name": "tiflash",
            "baseName": "tiflash",
            "type": "ClusterItemConfigComponentsTiflash"
        }    ];

    static getAttributeTypeMap() {
        return CreateClusterReqConfigComponents.attributeTypeMap;
    }
}

