/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItem } from './clusterItem';

/**
* GetClustersOfProjectResp is the response for getting clusters of project.
*/
export class GetClustersOfProjectResp {
    /**
    * The items of clusters in the project.
    */
    'items': Array<ClusterItem>;
    /**
    * The total number of clusters in the project.
    */
    'total': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ClusterItem>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetClustersOfProjectResp.attributeTypeMap;
    }
}

