/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The range and step of node quantity of the TiDB component in the cluster.
*/
export class ListProviderRegionsItemTidbInnerNodeQuantityRange {
    /**
    * The minimum node quantity of the component in the cluster.
    */
    'min'?: number;
    /**
    * The step of node quantity of the component in the cluster.
    */
    'step'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "min",
            "baseName": "min",
            "type": "number"
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListProviderRegionsItemTidbInnerNodeQuantityRange.attributeTypeMap;
    }
}

