/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListBackupItem } from './listBackupItem';

/**
* The response for listing backups of a cluster.
*/
export class ListBackupOfClusterResp {
    /**
    * The items of all backups.
    */
    'items'?: Array<ListBackupItem>;
    /**
    * The total number of backups in the project.
    */
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListBackupItem>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListBackupOfClusterResp.attributeTypeMap;
    }
}

