/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListProviderRegionsItemTikvInnerNodeQuantityRange } from './listProviderRegionsItemTikvInnerNodeQuantityRange';
import { ListProviderRegionsItemTikvInnerStorageSizeGibRange } from './listProviderRegionsItemTikvInnerStorageSizeGibRange';

export class ListProviderRegionsItemTikvInner {
    /**
    * The size of the TiKV component in the cluster.
    */
    'nodeSize'?: string;
    'nodeQuantityRange'?: ListProviderRegionsItemTikvInnerNodeQuantityRange;
    'storageSizeGibRange'?: ListProviderRegionsItemTikvInnerStorageSizeGibRange;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodeSize",
            "baseName": "node_size",
            "type": "string"
        },
        {
            "name": "nodeQuantityRange",
            "baseName": "node_quantity_range",
            "type": "ListProviderRegionsItemTikvInnerNodeQuantityRange"
        },
        {
            "name": "storageSizeGibRange",
            "baseName": "storage_size_gib_range",
            "type": "ListProviderRegionsItemTikvInnerStorageSizeGibRange"
        }    ];

    static getAttributeTypeMap() {
        return ListProviderRegionsItemTikvInner.attributeTypeMap;
    }
}

