/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* CreateRestoreResp is the response for restoring backup to a new cluster.
*/
export class OpenapiCreateRestoreResp {
    /**
    * The ID of the restore task.
    */
    'id'?: string;
    /**
    * The ID of the restored cluster. The restored cluster is the new cluster your backup data is restored to.
    */
    'clusterId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiCreateRestoreResp.attributeTypeMap;
    }
}

