/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListRestoreRespItem } from './listRestoreRespItem';

/**
* This response for list restore.
*/
export class OpenapiListRestoreOfProjectResp {
    /**
    * The items of all restore tasks.
    */
    'items'?: Array<ListRestoreRespItem>;
    /**
    * The total number of restore tasks in the project.
    */
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListRestoreRespItem>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiListRestoreOfProjectResp.attributeTypeMap;
    }
}

