/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListProviderRegionsItem } from './listProviderRegionsItem';

/**
* GetProviderRegionsResp is the response for getting provider regions.
*/
export class OpenapiListProviderRegionsResp {
    /**
    * Items of provider regions.
    */
    'items'?: Array<ListProviderRegionsItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListProviderRegionsItem>"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiListProviderRegionsResp.attributeTypeMap;
    }
}

