/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* ListProjectItem is the item of projects.
*/
export class OpenapiListProjectItem {
    /**
    * The ID of the project.
    */
    'id'?: string;
    /**
    * The ID of the TiDB Cloud organization to which the project belongs.
    */
    'orgId'?: string;
    /**
    * The name of the project.
    */
    'name'?: string;
    /**
    * The number of TiDB Cloud clusters deployed in the project.
    */
    'clusterCount'?: number;
    /**
    * The number of users in the project.
    */
    'userCount'?: number;
    /**
    * The creation time of the cluster in Unix timestamp seconds (epoch time).
    */
    'createTimestamp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "org_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "clusterCount",
            "baseName": "cluster_count",
            "type": "number"
        },
        {
            "name": "userCount",
            "baseName": "user_count",
            "type": "number"
        },
        {
            "name": "createTimestamp",
            "baseName": "create_timestamp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiListProjectItem.attributeTypeMap;
    }
}

