/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum OpenapiNodeStatus {
    Available = <any> 'NODE_STATUS_AVAILABLE',
    Unavailable = <any> 'NODE_STATUS_UNAVAILABLE',
    Creating = <any> 'NODE_STATUS_CREATING',
    Deleting = <any> 'NODE_STATUS_DELETING'
}
