/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClusterItemConfigComponents } from './clusterItemConfigComponents';

export class OpenapiGetClusterConfig {
    /**
    * The TiDB port for connection. The port must be in the range of 1024-65535 except 10080.
    */
    'port'?: number = 4000;
    'components'?: ClusterItemConfigComponents;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "ClusterItemConfigComponents"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiGetClusterConfig.attributeTypeMap;
    }
}

