/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateClusterComponentsComponentsTidb } from './updateClusterComponentsComponentsTidb';
import { UpdateClusterComponentsComponentsTiflash } from './updateClusterComponentsComponentsTiflash';
import { UpdateClusterComponentsComponentsTikv } from './updateClusterComponentsComponentsTikv';

export class OpenapiUpdateClusterComponents {
    'tidb'?: UpdateClusterComponentsComponentsTidb;
    'tikv'?: UpdateClusterComponentsComponentsTikv;
    'tiflash'?: UpdateClusterComponentsComponentsTiflash;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tidb",
            "baseName": "tidb",
            "type": "UpdateClusterComponentsComponentsTidb"
        },
        {
            "name": "tikv",
            "baseName": "tikv",
            "type": "UpdateClusterComponentsComponentsTikv"
        },
        {
            "name": "tiflash",
            "baseName": "tiflash",
            "type": "UpdateClusterComponentsComponentsTiflash"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiUpdateClusterComponents.attributeTypeMap;
    }
}

