/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListProjectItem } from './listProjectItem';

/**
* GetProjectsResp is the response for getting accessible projects.
*/
export class OpenapiListProjectsResp {
    /**
    * The items of accessible projects.
    */
    'items': Array<ListProjectItem>;
    /**
    * The total number of accessible projects.
    */
    'total': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListProjectItem>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiListProjectsResp.attributeTypeMap;
    }
}

