/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpenapiVPCPeeringConnection {
    /**
    * The host of VPC peering connection.
    */
    'host'?: string;
    /**
    * The TiDB port for connection. The port must be in the range of 1024-65535 except 10080.  **Limitations**: - For a Developer Tier cluster, only port `4000` is available.
    */
    'port'?: number = 4000;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiVPCPeeringConnection.attributeTypeMap;
    }
}

