/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpenapiUpdateTiKVComponent {
    /**
    * The storage size of a node in the cluster. You can get the minimum and maximum of storage size from the response of [List the cloud providers, regions and available specifications](#tag/Cluster/operation/ListProviderRegions).  **Limitations**: - You cannot decrease storage size for TiKV. - If your TiDB cluster is hosted by AWS, after changing the storage size of TiKV, you must wait at least six hours before you can change it again.
    */
    'storageSizeGib'?: number;
    /**
    * The number of nodes in the cluster. You can get the minimum and step of a node quantity from the response of [List the cloud providers, regions and available specifications](#tag/Cluster/operation/ListProviderRegions).  **Limitations**: - You cannot decrease node quantity for TiKV. - The `node_quantity` of TiKV must be a multiple of 3.
    */
    'nodeQuantity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "storageSizeGib",
            "baseName": "storage_size_gib",
            "type": "number"
        },
        {
            "name": "nodeQuantity",
            "baseName": "node_quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiUpdateTiKVComponent.attributeTypeMap;
    }
}

