/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateClusterComponentsComponents } from './updateClusterComponentsComponents';

/**
* UpdateClusterComponents is the request for updating cluster components.
*/
export class OpenapiUpdateClusterConfig {
    'components'?: UpdateClusterComponentsComponents;
    /**
    * Flag that indicates whether the cluster is paused. `true` means to pause the cluster, and `false` means to resume the cluster. For more details, refer to [Pause or Resume a TiDB Cluster](https://docs.pingcap.com/tidbcloud/pause-or-resume-tidb-cluster).  **Limitations:**  - The cluster can be paused only when the `cluster_status` is `\"AVAILABLE\"`. - The cluster can be resumed only when the `cluster_status` is `\"PAUSED\"`.
    */
    'paused'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "components",
            "baseName": "components",
            "type": "UpdateClusterComponentsComponents"
        },
        {
            "name": "paused",
            "baseName": "paused",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiUpdateClusterConfig.attributeTypeMap;
    }
}

