/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListProviderRegionsItemTiflashInnerNodeQuantityRange } from './listProviderRegionsItemTiflashInnerNodeQuantityRange';
import { ListProviderRegionsItemTiflashInnerStorageSizeGibRange } from './listProviderRegionsItemTiflashInnerStorageSizeGibRange';

export class OpenapiTiFlashProfile {
    /**
    * The size of the TiFlash component in the cluster.
    */
    'nodeSize'?: string;
    'nodeQuantityRange'?: ListProviderRegionsItemTiflashInnerNodeQuantityRange;
    'storageSizeGibRange'?: ListProviderRegionsItemTiflashInnerStorageSizeGibRange;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodeSize",
            "baseName": "node_size",
            "type": "string"
        },
        {
            "name": "nodeQuantityRange",
            "baseName": "node_quantity_range",
            "type": "ListProviderRegionsItemTiflashInnerNodeQuantityRange"
        },
        {
            "name": "storageSizeGibRange",
            "baseName": "storage_size_gib_range",
            "type": "ListProviderRegionsItemTiflashInnerStorageSizeGibRange"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiTiFlashProfile.attributeTypeMap;
    }
}

