/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpenapiTiDBNodeMap {
    /**
    * The name of a node in the cluster.
    */
    'nodeName'?: string;
    /**
    * The availability zone of a node in the cluster.
    */
    'availabilityZone'?: string;
    /**
    * The size of the TiDB component in the cluster.
    */
    'nodeSize'?: string;
    /**
    * The total vCPUs of a node in the cluster. If the `cluster_type` is `\"DEVELOPER\"`, `vcpu_num` is always 0.
    */
    'vcpuNum'?: number;
    /**
    * The RAM size of a node in the cluster. If the `cluster_type` is `\"DEVELOPER\"`, `ram_bytes` is always 0.
    */
    'ramBytes'?: string;
    /**
    * The status of a node in the cluster.
    */
    'status'?: OpenapiTiDBNodeMap.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodeName",
            "baseName": "node_name",
            "type": "string"
        },
        {
            "name": "availabilityZone",
            "baseName": "availability_zone",
            "type": "string"
        },
        {
            "name": "nodeSize",
            "baseName": "node_size",
            "type": "string"
        },
        {
            "name": "vcpuNum",
            "baseName": "vcpu_num",
            "type": "number"
        },
        {
            "name": "ramBytes",
            "baseName": "ram_bytes",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OpenapiTiDBNodeMap.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiTiDBNodeMap.attributeTypeMap;
    }
}

export namespace OpenapiTiDBNodeMap {
    export enum StatusEnum {
        Available = <any> 'NODE_STATUS_AVAILABLE',
        Unavailable = <any> 'NODE_STATUS_UNAVAILABLE',
        Creating = <any> 'NODE_STATUS_CREATING',
        Deleting = <any> 'NODE_STATUS_DELETING'
    }
}
