/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum OpenapiClusterStatus {
    Available = <any> 'AVAILABLE',
    Creating = <any> 'CREATING',
    Modifying = <any> 'MODIFYING',
    Paused = <any> 'PAUSED',
    Resuming = <any> 'RESUMING',
    Unavailable = <any> 'UNAVAILABLE',
    Importing = <any> 'IMPORTING'
}
