/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListProviderRegionsItemTidbInner } from './listProviderRegionsItemTidbInner';
import { ListProviderRegionsItemTiflashInner } from './listProviderRegionsItemTiflashInner';
import { ListProviderRegionsItemTikvInner } from './listProviderRegionsItemTikvInner';

/**
* ListProviderRegionsItem is the item of provider regions.
*/
export class OpenapiListProviderRegionsItem {
    /**
    * The cluster type. - `\"DEVELOPER\"`: a [Developer Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#developer-tier) cluster - `\"DEDICATED\"`: a [Dedicated Tier](https://docs.pingcap.com/tidbcloud/select-cluster-tier#dedicated-tier) cluster
    */
    'clusterType'?: OpenapiListProviderRegionsItem.ClusterTypeEnum;
    /**
    * The cloud provider on which your TiDB cluster is hosted. - `\"AWS\"`: the Amazon Web Services cloud provider - `\"GCP\"`: the Google Cloud Platform cloud provider
    */
    'cloudProvider'?: OpenapiListProviderRegionsItem.CloudProviderEnum;
    /**
    * The region in which your TiDB cluster is hosted.  For the detailed information on each region, refer to the documentation of the corresponding cloud provider ([AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) | [GCP](https://cloud.google.com/about/locations#americas)).  For example, `\"us-west-2\"` refers to Oregon for AWS.
    */
    'region'?: string;
    /**
    * The list of TiDB specifications in the region.
    */
    'tidb'?: Array<ListProviderRegionsItemTidbInner>;
    /**
    * The list of TiKV specifications in the region.
    */
    'tikv'?: Array<ListProviderRegionsItemTikvInner>;
    /**
    * The list of TiFlash specifications in the region.
    */
    'tiflash'?: Array<ListProviderRegionsItemTiflashInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clusterType",
            "baseName": "cluster_type",
            "type": "OpenapiListProviderRegionsItem.ClusterTypeEnum"
        },
        {
            "name": "cloudProvider",
            "baseName": "cloud_provider",
            "type": "OpenapiListProviderRegionsItem.CloudProviderEnum"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "tidb",
            "baseName": "tidb",
            "type": "Array<ListProviderRegionsItemTidbInner>"
        },
        {
            "name": "tikv",
            "baseName": "tikv",
            "type": "Array<ListProviderRegionsItemTikvInner>"
        },
        {
            "name": "tiflash",
            "baseName": "tiflash",
            "type": "Array<ListProviderRegionsItemTiflashInner>"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiListProviderRegionsItem.attributeTypeMap;
    }
}

export namespace OpenapiListProviderRegionsItem {
    export enum ClusterTypeEnum {
        Dedicated = <any> 'DEDICATED',
        Developer = <any> 'DEVELOPER'
    }
    export enum CloudProviderEnum {
        Aws = <any> 'AWS',
        Gcp = <any> 'GCP'
    }
}
