/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateClusterReqConfigComponents } from './createClusterReqConfigComponents';
import { CreateClusterReqConfigIpAccessListInner } from './createClusterReqConfigIpAccessListInner';

export class OpenapiClusterConfig {
    /**
    * The root password to access the cluster. It must be 8-64 characters.
    */
    'rootPassword': string;
    /**
    * The TiDB port for connection. The port must be in the range of 1024-65535 except 10080.  **Limitations**: - For a Developer Tier cluster, only port `4000` is available.
    */
    'port'?: number = 4000;
    'components'?: CreateClusterReqConfigComponents;
    /**
    * A list of IP addresses and Classless Inter-Domain Routing (CIDR) addresses that are allowed to access the TiDB Cloud cluster via [standard connection](https://docs.pingcap.com/tidbcloud/connect-to-tidb-cluster#connect-via-standard-connection).
    */
    'ipAccessList'?: Array<CreateClusterReqConfigIpAccessListInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rootPassword",
            "baseName": "root_password",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "CreateClusterReqConfigComponents"
        },
        {
            "name": "ipAccessList",
            "baseName": "ip_access_list",
            "type": "Array<CreateClusterReqConfigIpAccessListInner>"
        }    ];

    static getAttributeTypeMap() {
        return OpenapiClusterConfig.attributeTypeMap;
    }
}

