/**
 * TiDB Cloud API
 * *TiDB Cloud API is in beta.
 *
 * The version of the OpenAPI document: v1-beta
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateClusterComponents } from './updateClusterComponents';

/**
* UpdateClusterReq is the request for updating cluster.
*/
export class UpdateClusterReq {
    'config': UpdateClusterComponents;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "UpdateClusterComponents"
        }    ];

    static getAttributeTypeMap() {
        return UpdateClusterReq.attributeTypeMap;
    }
}

